# Generated by Django 5.1.2 on 2024-12-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='sin direccion', max_length=250, verbose_name='Direccion'),
        ),
    ]
