# Generated by Django 5.1.2 on 2024-12-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cliente',
            new_name='vendedor',
        ),
    ]
